#!/usr/bin/env python3
"""Parse hololive_member_tags.md into bot_data.py (MEMBERS + TAGS)."""
import os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "hololive_member_tags.md")
OUT = os.path.join(REPO, "bot_data.py")

HEADER = re.compile(r"^\*\*(.+?)\*\*\s*\(([^,]+),\s*([^)]+)\)\s*—\s*(?:\d+ tags?:?|no tag.*)$")

members = {}   # name -> {"lang","branch","gen"}
tags = {}      # name -> {source: [tag,...]}
order = []
source = None
cur = None

for line in open(SRC, encoding="utf-8"):
    s = line.strip()
    if s.startswith("## "):
        source = s[3:].strip()
        continue
    if s.startswith("### "):
        lang = s[4:].split(" —")[0].strip()
        continue
    m = HEADER.match(s)
    if m:
        name, branch, gen = m.group(1), m.group(2), m.group(3)
        if name not in members:
            members[name] = {"lang": lang, "branch": branch, "gen": gen}
            order.append(name)
            tags[name] = {}
        tags[name][source] = []
        cur = (name, source)
        continue
    if cur and s and s != cur[0]:
        tags[cur[0]][cur[1]] += [t.strip() for t in s.split(",") if t.strip()]

with open(OUT, "w", encoding="utf-8") as f:
    f.write("# Generated by scripts/gen_bot_data.py from hololive_member_tags.md — do not edit.\n")
    f.write("MEMBERS = {\n")
    for name in order:
        f.write(f"    {name!r}: {members[name]!r},\n")
    f.write("}\n\n")
    f.write("TAGS = {\n")
    for name in order:
        f.write(f"    {name!r}: {{\n")
        for src, tl in tags[name].items():
            f.write(f"        {src!r}: {tl!r},\n")
        f.write("    },\n")
    f.write("}\n")

pair_count = sum(1 for t in tags.values() for _ in t)
print(f"members: {len(members)}")
print(f"sources: {sorted({s for t in tags.values() for s in t})}")
print(f"member-source pairs: {pair_count}")
if len(members) != 87:
    print(f"ERROR: expected 87 members, got {len(members)}")
    sys.exit(1)
